begin;
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (1256,'CLARIN','Domingo','{6}'::smallint[],'C',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=923 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (923,'LA NACION','Domingo','{6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (1322,'CLARIN','Sábado','{5}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (897,'CRONICA','Domingo','{6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (897,'POPULAR','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (15,'LA NACION','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (15,'CLARIN','Sábado','{5}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (713,'CLARIN','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (734,'LA NACION','Domingo','{6}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (12,'LA NACION','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=838 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (838,'LA NACION','Miércoles, Jueves, Sábado, Domingo','{2,3,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (82,'LA NACION','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'C',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=76 and not anulado and hasta is null and upper(publicacion)=upper('CRONICA');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (76,'CRONICA','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'C',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=109 and not anulado and hasta is null and upper(publicacion)=upper('CLARIN');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (109,'CLARIN','Miércoles, Jueves, Viernes, Sábado','{2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=86 and not anulado and hasta is null and upper(publicacion)=upper('QUIJOTE');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (86,'QUIJOTE','Miércoles','{2}'::smallint[],'C',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=86 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (86,'LA NACION','Sábado','{5}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=97 and not anulado and hasta is null and upper(publicacion)=upper('CLARIN');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (97,'CLARIN','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (119,'LA NACION','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (847,'LA NACION','Sábado y domingo','{5,6}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (527,'CARAS','Jueves','{3}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (1367,'LA NACION','Domingo','{6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (254,'CLARIN','De lunes a viernes','{0,1,2,3,4}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (558,'CLARIN','Domingo','{6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (684,'LA NACION','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (684,'CLARIN','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (265,'LA NACION','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'C',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (279,'POPULAR','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=1173 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (1173,'LA NACION','Sábado y domingo','{5,6}'::smallint[],'C',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=304 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (304,'LA NACION','Viernes, Sábado, Domingo','{4,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=995 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (995,'LA NACION','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (223,'HOLA ARGENTINA','Jueves','{3}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=1219 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (1219,'LA NACION','Miércoles, Jueves, Viernes, Sábado','{2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=369 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (369,'LA NACION','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'C',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=146 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (146,'LA NACION','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (543,'LA NACION','Sábado','{5}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=91 and not anulado and hasta is null and upper(publicacion)=upper('CLARIN');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (91,'CLARIN','Martes y Jueves','{1,3}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=91 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (91,'LA NACION','Sábado','{5}'::smallint[],'S',1,date '2026-09-01','hojas');
update public.suscripciones set hasta=date '2026-09-01', modificado_en=now() where cliente_id=815 and not anulado and hasta is null and upper(publicacion)=upper('LA NACION');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (815,'LA NACION','De lunes a sábado','{0,1,2,3,4,5}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (773,'LA NACION','Domingo','{6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (458,'LA NACION','Todos los días','{0,1,2,3,4,5,6}'::smallint[],'S',1,date '2026-09-01','hojas');
insert into public.suscripciones(cliente_id,publicacion,dias_texto,dias,via,cantidad,desde,origen) values (472,'CLARIN','Domingo','{6}'::smallint[],'S',1,date '2026-09-01','hojas');
commit;
select count(*) filter (where origen='hojas') nuevas, count(*) filter (where hasta=date '2026-09-01') cerradas from public.suscripciones;